name: application_v2
description: CHARGE LINK - Smart Charging Controller
publish_to: 'none'
version: 2.0.0+1

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6

  flutter_blue_plus: ^2.3.12
  battery_plus: ^6.0.2
  fl_chart: ^0.69.0
  permission_handler: ^13.0.1
  provider: ^6.1.2
  google_fonts: ^6.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
